name: CI

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules

  lint:
    runs-on: ubuntu-latest
    needs: install # This ensures that the install job runs before this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ls -la
        run: ls -la

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: ls -la 1
        run: ls -la

      - name: Run ESLint
        run: ls -la && yarn lint

  test:
    runs-on: ubuntu-latest
    needs: install # This ensures that the install job runs before this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Run tests
        run: yarn test
