name: CI

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules/

  lint:
    runs-on: ubuntu-latest
    needs: install # This ensures that the install job runs before this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run ESLint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: install # This ensures that the install job runs before this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run tests
        run: yarn test
