name: CI

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules/

  test:
    runs-on: ubuntu-latest
    needs: install # This ensures that the install job runs before this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: install # This ensures that the install job runs before this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Build project
        run: yarn build
  cleanup:
    runs-on: ubuntu-latest
    needs: [test, build] # This ensures that the cleanup job runs after test and build jobs
    steps:
      - name: Delete node_modules artifact
        uses: actions/delete-artifact@v2
        with:
          name: node-modules
