name: CI

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test --ci --watchAll=false

      - name: Run eslint
        run: yarn lint

      - name: Run prettier
        run: yarn prettier . --debug-check
